# Home
D .
    .zshrc

# Config
D .config
    alacritty
    dunst
    gtk-3.0
    hypr
    wal
    waybar
    wireplumber
    wlogout
    wofi
    xsettingsd
    chrome-flags.conf
    chromium-flags.conf
    electron-flags.conf
    electron13-flags.conf
    electron25-flags.conf
# (Leave this line)