###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Binds/ for more

# System Bindings
bind = $superMod, Q, killactive,

bind = $superMod, L, exec, $scripts/lock.sh
bind = $shiftMod, L, exec, hyprctl dispatch exit 0

bind = $shiftMod, Return, fullscreen
bind = $shiftMod, F, togglefloating

bind = $superMod, V, exec, $scripts/cliphist.sh
bind = $superMod, R, exec, hyprland-run
bind = $shiftMod, S, exec, hyprshot --mode region --output-fol.der ~/Pictures/
bind = $shiftMod, W, exec, $scripts/change-wallpaper.sh
bind = $superMod, PERIOD, exec, flatpak run it.mijorus.smile

# Applications
bind = $superMod, T, exec, $terminal
bind = $superMod, Space, exec, $menu
bind = $superMod, F, exec, $fileManager
bind = $superMod, B, exec, $browser
bind = $ctrlMod, Space, exec, $emojiPicker
bind = ,XF86Calculator, exec, $calculator
bind = ,XF86Launch2, exec, $softwareCenter
bind = $superMod, P, exec, $notificationPanel

# Personal
bind = $shiftMod, Space, exec, 1password --quick-access

# Move focus with mainMod + arrow keys
bind = $superMod, left, movefocus, l
bind = $superMod, right, movefocus, r
bind = $superMod, up, movefocus, u
bind = $superMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $superMod, 1, workspace, 1
bind = $superMod, 2, workspace, 2
bind = $superMod, 3, workspace, 3
bind = $superMod, 4, workspace, 4
bind = $superMod, 5, workspace, 5
bind = $superMod, 6, workspace, 6
bind = $superMod, 7, workspace, 7
bind = $superMod, 8, workspace, 8
bind = $superMod, 9, workspace, 9
bind = $superMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $superMod SHIFT, 1, movetoworkspace, 1
bind = $superMod SHIFT, 2, movetoworkspace, 2
bind = $superMod SHIFT, 3, movetoworkspace, 3
bind = $superMod SHIFT, 4, movetoworkspace, 4
bind = $superMod SHIFT, 5, movetoworkspace, 5
bind = $superMod SHIFT, 6, movetoworkspace, 6
bind = $superMod SHIFT, 7, movetoworkspace, 7
bind = $superMod SHIFT, 8, movetoworkspace, 8
bind = $superMod SHIFT, 9, movetoworkspace, 9
bind = $superMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
# bind = $superMod, S, togglespecialworkspace, magic
# bind = $superMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $superMod, mouse_down, workspace, e+1
bind = $superMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $superMod, mouse:272, movewindow
bindm = $superMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bind = , XF86AudioPlay, exec, swayosd-client --playerctl play-pause
bind = , XF86AudioNext, exec, swayosd-client --playerctl next
bind = , XF86AudioPrev, exec, swayosd-client --playerctl previous
bind = , XF86AudioStop, exec, swayosd-client --playerctl stop

# Volume controls with SwayOSD
bind = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bind = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bind = , XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle

# Brightness controls with SwayOSD
bind = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
bind = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower



# Lid Switch
bindl = ,switch:Lid Switch, exec, $scripts/lid-close.sh