###################
### VARIABLES ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Directories
$launchers = ~/.config/hypr/launchers
$scripts = ~/.config/hypr/scripts

# Keyboard Modifiers
$superMod = SUPER
$altMod = SUPER ALT
$ctrlMod = SUPER CTRL
$shiftMod = SUPER SHIFT

# Programs
$terminal = alacritty
$fileManager = nautilus
$menu = $scripts/wofi.sh
$browser = flatpak run app.zen_browser.zen
$emojiPicker = smile
$softwareCenter = gnome-software
$calculator = kill -9 $(pidof gnome-calculator); gnome-calculator
$notificationPanel = swaync-client -t
$colorPicker = hyprpicker | wl-copy
