##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps
windowrule {
  name = suppress-maximize
  match:class = .*
  
  suppress_event = maximize
}

# Fix dragging issues with XWayland
windowrule {
  name = xwayland-drag-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
  
  no_initial_focus = on
}

# Smile - float
windowrule {
  name = smile-float
  match:title = ^(Smile)
  
  float = on
}

# Zenity - float
windowrule {
  name = zenity-float
  match:class = ^(zenity)
  
  float = on
}

# Firefox Picture-in-Picture
windowrule {
  name = firefox-pip
  match:class = ^(firefox)$
  match:title = ^(Picture-in-Picture)$
  
  pin = on
  float = on
}

# Wallpaper selector
windowrule {
  name = wallpaper-selector
  match:title = ^(Select a new Wallpaper)
  
  float = on
}

# Network Connections
windowrule {
  name = network-connections
  match:title = ^(Network Connections)
  
  float = on
  size = 25% 50%
}

# Bluetooth Devices
windowrule {
  name = bluetooth-devices
  match:title = ^(Bluetooth Devices)
  
  float = on
  size = 25% 50%
}

# Calculator
windowrule {
  name = calculator
  match:title = ^(Calculator)
  
  float = on
  size = 25% 50%
}