# Home
[.]
.zshrc

# Config
[.config]
alacritty
dunst
gtk-3.0
hypr
wal
waybar
wireplumber
wlogout
wofi
xsettingsd
chrome-flags.conf
chromium-flags.conf
electron-flags.conf
electron13-flags.conf
electron25-flags.conf

[.local]
bin

# (Leave this line)