[pacman]

# Hyprland Ecosystem
hyprland
hypridle
hyprlock
hyprpaper

# Hyprland Must-Have
xdg-desktop-portal-hyprland
xdg-desktop-portal-gtk
polkit-kde-agent
qt5-wayland
qt6-wayland

# Desktop Manager
greetd
greetd-tuigreet

# Audio
pipewire
pipewire-alsa
pipewire-jack
wireplumber

# Notification
mako
inotify-tools

# Terminal
alacritty

# Status Bar
waybar

# App Menu
wofi

# File Manager
thunar
thunar-archive-plugin
thunar-media-tags-plugin
thunar-volman
tumbler
file-roller
gvfs

# Network & Bluetooth
networkmanager
network-manager-applet
bluez
bluez-utils

# Theming
python-pywal
xsettingsd
nwg-look
qt5ct
qt6ct

# Utilities
brightnessctl
cliphist
udiskie
tlp
tlp-rdw
bc

# Fonts
ttf-roboto
ttf-nerd-fonts-symbols-common
ttf-fira-code
ttf-firacode-nerd
noto-fonts-emoji

# Flatpak
flatpak
gnome-software

# Needed AUR packages
[aur]
blueman
hyprshot
libinput-gestures
tlpui

# Optional packages
[pacman-opt]
btop
usbutils
easyeffects
lsp-plugins-lv2
fastfetch
neovim
discord
evince
loupe

[aur-opt]
1password
google-chrome
spotify
visual-studio-code-bin

