[pacman]

# Hyprland Ecosystem
hyprland
hypridle
hyprlock
hyprpaper

# Hyprland Must-Have
dunst

xdg-desktop-portal-hyprland
xdg-desktop-portal-gtk
xdg-desktop-portal-kde
xdg-desktop-portal-wlr
polkit-kde-agent
qt5-wayland
qt6-wayland

# Audio
pipewire
pipewire-alsa
pipewire-jack
wireplumber

# Desktop Manager
sddm

# Terminal
alacritty

# File Manager
thunar
thunar-archive-plugin
thunar-media-tags-plugin
thunar-volman
tumbler
file-roller
gvfs

# Status Bar
waybar

# App Menu
wofi

# Bluetooth
bluez
bluez-utils

# GTK/QT
nwg-look
qt5ct
qt6ct

# Utilities
brightnessctl
inotify-tools
pavucontrol
network-manager-applet
cliphist
udiskie
xsettingsd
easyeffects

# Fonts
otf-font-awesome
ttf-fira-code
ttf-firacode-nerd
ttf-jetbrains-mono
ttf-jetbrains-mono-nerd
ttf-roboto
noto-fonts-emoji

# Flatpak
flatpak
gnome-software

# Optional
btop
usbutils
easyeffects
neofetch
neovim
discord

[aur]

# Needed
blueman
libinput-gestures
hyprshot
wlogout

# Optional
1password
google-chrome
spotify
visual-studio-code-bin

