#!/bin/bash

#################################################################################
#                                                                               #
#   This script has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this script) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

config_dir="$HOME/.config"
cache_dir="$HOME/.cache"

function printc() {
	# dunstify -a "Color Palette" -u normal "$1"
	echo -e "$1"
}

# Generating theme using PyWal
printc "Generating theme..."
wal -i "$config_dir/hypr/wallpapers/current.png"

# *** Applying theme ****
printc "Applying theme..."

# Reloading Hyprpaper
printc "\tHyprpaper..."
killall hyprpaper
nohup hyprpaper &> /dev/null &

# Hyprland
printc "\tHyprland..."
hyprctl reload

# Waybar
printc "\tWaybar..."
killall waybar
nohup waybar &> /dev/null &

# Alacritty
printc "\tAlacritty..."
echo "#DO NOT EDIT THIS FILE, EDIT THE .base ONE INSTEAD!!!" > "$config_dir/alacritty/alacritty.toml"
cat "$config_dir/alacritty/alacritty.toml.base" >> "$config_dir/alacritty/alacritty.toml"
cat "$cache_dir/wal/colors-alacritty.toml" >> "$config_dir/alacritty/alacritty.toml"

# oomox
printc "\toomox..."
/opt/oomox/plugins/theme_oomox/change_color.sh $HOME/.cache/wal/colors-oomox

# *** DONE ***
printc "Done!"
