#!/bin/bash

#################################################################################
#                                                                               #
#   This script has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this script) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

config_dir="$HOME/.config"
cache_dir="$HOME/.cache"

function printc() {
	# dunstify -a "Color Palette" -u normal "$1"
	echo -e "$1"
}

# Generating theme using PyWal
printc "Generating theme..."
wal -i "$config_dir/hypr/wallpapers/current.png" -q -s -t

# *** Applying theme ****
printc "Applying theme..."

# Reloading Hyprpaper
printc "\tHyprpaper..."
killall hyprpaper
nohup hyprpaper &> /dev/null &

# Hyprland
printc "\tHyprland..."
hyprctl reload

# Waybar
printc "\tWaybar..."
killall waybar
nohup waybar &> /dev/null &

# Alacritty
printc "\tAlacritty..."
echo "#DO NOT EDIT THIS FILE, EDIT THE .base ONE INSTEAD!!!" > "$config_dir/alacritty/alacritty.toml"
cat "$config_dir/alacritty/alacritty.base.toml" >> "$config_dir/alacritty/alacritty.toml"
cat "$cache_dir/wal/colors-alacritty.toml" >> "$config_dir/alacritty/alacritty.toml"

# oomox
printc "\toomox..."
/opt/oomox/plugins/theme_oomox/change_color.sh $HOME/.cache/wal/colors-oomox

# Switching oomox gtk dark/light theme
theme_dir="$HOME/.themes/oomox-colors-oomox"

# GTK 3.0
gtk_dir="gtk-3.0"
cp "$theme_dir/$gtk_dir/gtk-dark.css" 		"$theme_dir/$gtk_dir/gtk-dark.css.bak"
mv "$theme_dir/$gtk_dir/gtk.css" 		"$theme_dir/$gtk_dir/gtk-dark.css"
mv "$theme_dir/$gtk_dir/gtk-dark.css.bak" 	"$theme_dir/$gtk_dir/gtk.css"

# GTK 3.20
gtk_dir="gtk-3.20"
cp "$theme_dir/$gtk_dir/gtk-dark.css" 		"$theme_dir/$gtk_dir/gtk-dark.css.bak"
mv "$theme_dir/$gtk_dir/gtk.css" 		"$theme_dir/$gtk_dir/gtk-dark.css"
mv "$theme_dir/$gtk_dir/gtk-dark.css.bak" 	"$theme_dir/$gtk_dir/gtk.css"

# xsettingsd
dpi=$(cat "$HOME/.config/xsettingsd/xsettingsd.conf" | tail -n1 | cut -d ' ' -f1 | cut -d '/' -f2)
if [[ dpi == "DPI" ]]; then
	echo "Xft/DPI 225280" >> "$HOME/.config/xsettingsd/xsettingsd.conf"
fi


# *** DONE ***
printc "Done!"
