#!/bin/bash

#################################################################################
#                                                                               #
#   This script has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this script) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

# Setting config and cache dir
config_dir="$HOME/.config"
cache_dir="$HOME/.cache"

# Generating theme using PyWal
rm -r "$cache_dir/wal"
wal -i "$config_dir/hypr/wallpapers/current.png" -q -s -t

# Include pywal colors
. "$cache_dir/wal/colors.sh"

# *** Applying theme *** #

### HYPRPAPER ###
killall hyprpaper
nohup hyprpaper &> /dev/null &

### HYPRLAND ###
hyprctl reload

### WAYBAR ###
killall waybar
nohup waybar &> /dev/null &

### ALAXCRITTY ###
echo "# DO NOT EDIT THIS FILE, EDIT THE alacritty.base.toml INSTEAD!!!" > "$config_dir/alacritty/alacritty.toml"
cat "$config_dir/alacritty/alacritty.base.toml" >> "$config_dir/alacritty/alacritty.toml"
cat "$cache_dir/wal/colors-alacritty.toml" >> "$config_dir/alacritty/alacritty.toml"

### MAKO ###
mako_config="$config_dir/mako/config"

# Associative array, color name -> color code.
declare -A colors
colors=(
    ["background-color"]="${background}"
    ["text-color"]="$foreground"
    ["border-color"]="$color13"
)

for color_name in "${!colors[@]}"; do
  # replace first occurance of each color in config file
  sed -i "0,/^$color_name.*/{s//$color_name=${colors[$color_name]}/}" $mako_config
done

### DONE ###
notify-send -a "System" "Palette changed!"
