#!/bin/bash

#################################################################################
#                                                                               #
#   This script has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this script) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

# Setting config and cache dir
config_dir="$HOME/.config"
cache_dir="$HOME/.cache"

# Generating theme using PyWal
rm -r "$cache_dir/wal"
wal -i "$config_dir/hypr/wallpapers/current.png" -q -s -t

# Include pywal colors
. "$cache_dir/wal/colors.sh"

# *** Applying theme *** #

### HYPRPAPER ###
killall hyprpaper
nohup hyprpaper &> /dev/null &

### HYPRLAND ###
hyprctl reload

### WAYBAR ###
killall waybar
nohup waybar &> /dev/null &

### ALAXCRITTY ###
echo "# DO NOT EDIT THIS FILE, EDIT THE alacritty.base.toml INSTEAD!!!" > "$config_dir/alacritty/alacritty.toml"
cat "$config_dir/alacritty/alacritty.base.toml" >> "$config_dir/alacritty/alacritty.toml"
cat "$cache_dir/wal/colors-alacritty.toml" >> "$config_dir/alacritty/alacritty.toml"

### OOMOX ###
/opt/oomox/plugins/theme_oomox/change_color.sh $cache_dir/wal/colors-oomox

# Switching oomox gtk dark/light theme
theme_dir="$HOME/.themes/oomox-colors-oomox"

# GTK 3.0
gtk_dir="gtk-3.0"
cp "$theme_dir/$gtk_dir/gtk-dark.css" 		"$theme_dir/$gtk_dir/gtk-dark.css.bak"
mv "$theme_dir/$gtk_dir/gtk.css" 		"$theme_dir/$gtk_dir/gtk-dark.css"
mv "$theme_dir/$gtk_dir/gtk-dark.css.bak" 	"$theme_dir/$gtk_dir/gtk.css"

# GTK 3.20
gtk_dir="gtk-3.20"
cp "$theme_dir/$gtk_dir/gtk-dark.css" 		"$theme_dir/$gtk_dir/gtk-dark.css.bak"
mv "$theme_dir/$gtk_dir/gtk.css" 		"$theme_dir/$gtk_dir/gtk-dark.css"
mv "$theme_dir/$gtk_dir/gtk-dark.css.bak" 	"$theme_dir/$gtk_dir/gtk.css"

### XSETTINGSD ###
xsd_config="$config_dir/xsettingsd/xsettingsd.conf"
dpi=$(cat "$xsd_config" | tail -n1 | cut -d ' ' -f1 | cut -d '/' -f2)

# Applying DPI if removed..
if [[ "$dpi" != "DPI" ]]; then
	echo "Xft/DPI 225280" >> $xsd_config
	systemctl --user restart xsettingsd.service
fi

### MAKO ###
mako_config="$config_dir/mako/config"

# Associative array, color name -> color code.
declare -A colors
colors=(
    ["background-color"]="${background}"
    ["text-color"]="$foreground"
    ["border-color"]="$color13"
)

for color_name in "${!colors[@]}"; do
  # replace first occurance of each color in config file
  sed -i "0,/^$color_name.*/{s//$color_name=${colors[$color_name]}/}" $mako_config
done

### DONE ###
notify-send -a "System" "Palette changed!"
