# Loading wallpaper manager
exec-once = hyprpaper

# Wallpaper
$wallpaper1 = ~/.config/hypr/wallpapers/linus-torvalds.png

# Preloading the wallpaper...
preload = $wallpaper1

# Setting the wallpaper
wallpaper = eDP-1, $wallpaper1

# Enable splash text rendering over the wallpaper
splash = false

# Fully disable ipc
# ipc = off

