# Loading wallpaper manager
exec-once = hyprpaper

# Wallpaper
$wallpaper = ~/.config/hypr/wallpapers/current.png

# Preloading the wallpaper...
preload = $wallpaper

# Setting the wallpaper
wallpaper = eDP-1, $wallpaper
wallpaper = DP-1, $wallpaper

# Enable splash text rendering over the wallpaper
splash = false

# Fully disable ipc
# ipc = off

