# STARTUP

# Authentication dialog for GUI Apps
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Notification Daemon
exec-once = dunst

# Top Bar
exec-once = ~/.config/hypr/scripts/WaybarLaunch.sh

# Connections Applet (tray)
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Pipewire restart (To avoid bugs)
exec-once = systemctl --user restart pipewire.service

# Password Manager (1Password)
exec-once = 1password --silent

# IDLE
exec-once = hypridle

# Screen Brightness
exec-once = brightnessctl set 80%

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store # Text
exec-once = wl-paste --type image --watch cliphist store # Images
