# Scripts Directory
$scriptsDir = ~/.config/hypr/scripts

# Applications
$terminal = alacritty
$fileManager = thunar
$browser = google-chrome-stable
$menu = $scriptsDir/WofiLaunch.sh

# Commands
$lock = hyprlock
$logout = $scriptsDir/Logout.sh
