# Applications
$terminal = alacritty
$fileManager = thunar
$browser = google-chrome-stable
$menu = wofi --show drun --allow-images -a -i --prompt "Search..."

# Commands
$lock = hyprlock
$logout = ~/.config/hypr/scripts/Logout.sh
