# Suppress Maximize
windowrulev2 = suppressevent maximize, class:.*

# 1Password
windowrulev2 = float, title:(1Password)
windowrulev2 = size 70% 70%, title:(1Password)
windowrulev2 = center, title:(1Password)

# Electron Dev
windowrulev2 = float, title:(WayOut)
windowrulev2 = center, title:(WayOut)
