# HYPRLAND

#################################################################################
#                                                                               #
#   This config has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this config) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

# Variables
source = ~/.config/hypr/variables.conf

# ENVIRONMENT
source = ~/.config/hypr/env.conf

# MONITOR
# monitor=name,resolution,position,scale
monitor=eDP-1, 2880x1800, 0x0, 2, bitdepth, 10
monitor=DP-1, 1920x1080, -1920x0, 1

# STARTUP
source = ~/.config/hypr/startup.conf

# PyWal Loading
source = ~/.cache/wal/colors-hypr.conf

# GENERAL
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2
    col.active_border = $color3 $color4 $color5 $color6 30deg
    col.inactive_border = $backgound

    layout = dwindle
    allow_tearing = false
}

# DECORATION
decoration {
    rounding = 8
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = no
}

# ANIMATIONS
animations {
    enabled = yes

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# INPUT
input {
    kb_layout = it
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.8
        # clickfinger_behavior = true # Enables Three-Fingers Middle-Click
        # tap-to-click = false
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}

# GESTURES
gestures {
    workspace_swipe = true
    workspace_swipe_invert = true
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 1300
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_min_speed_to_force = 8
    workspace_swipe_create_new = true
}

# LAYOUTS
dwindle {
    pseudotile = yes # master switch for pseudotiling
    preserve_split = yes # you probably want this
}

master {
    new_is_master = true
}

# MISC
misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

}

# XWayland
xwayland {
  force_zero_scaling = true     # Forces Scale=1 on XWayland Apps
  use_nearest_neighbor = false # True = pixelated, False = blurry
}

# WINDOWRULE
source = ~/.config/hypr/windowrule.conf

# KEYBINDS
source = ~/.config/hypr/keybinds.conf
