# KEYBINDS

#################################################################################
#                                                                               #
#   This config has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this config) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

# KEYBINDS
$mainMod = SUPER
$shiftMod = SUPER SHIFT
$ctrlMod = SUPER CTRL
$altMod = SUPER ALT

# Hyprland Commands
bind = $mainMod, Q, killactive, 
bind = $shiftMod, T, togglefloating
bind = $shiftMod, F, fullscreen

# Commands
bind = $shiftMod, Q, exec, $lock
bind = $shiftMod, L, exec, $logout

# Applications
bind = $mainMod, Space, exec, $menu
bind = $mainMod, T, exec, $terminal
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, B, exec, $browser

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $shiftMod, 1, movetoworkspace, 1
bind = $shiftMod, 2, movetoworkspace, 2
bind = $shiftMod, 3, movetoworkspace, 3
bind = $shiftMod, 4, movetoworkspace, 4
bind = $shiftMod, 5, movetoworkspace, 5
bind = $shiftMod, 6, movetoworkspace, 6
bind = $shiftMod, 7, movetoworkspace, 7
bind = $shiftMod, 8, movetoworkspace, 8
bind = $shiftMod, 9, movetoworkspace, 9
bind = $shiftMod, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move
bindm = $mainMod, mouse:272, movewindow
bind = $ctrlMod, left, movewindow, l
bind = $ctrlMod, right, movewindow, r
bind = $ctrlMod, up, movewindow, u
bind = $ctrlMod, down, movewindow, d

# Resize
binde = $shiftMod, left, resizeactive, -20 0
binde = $shiftMod, right, resizeactive, 20 0
binde = $shiftMod, up, resizeactive, 0 -20
binde = $shiftMod, down, resizeactive, 0 20

# Display Brightness
binde = , XF86MonBrightnessUp, exec, $scriptsDir/CmdBrightness.sh D 5
binde = , XF86MonBrightnessDown, exec, $scriptsDir/CmdBrightness.sh D -5

# Keyboard Brightness
binde = , XF86KbdBrightnessUp, exec, $scriptsDir/CmdBrightness.sh K 10
binde = , XF86KbdBrightnessDown, exec, $scriptsDir/CmdBrightness.sh K -10

# Volume
binde = , XF86AudioRaiseVolume, exec, $scriptsDir/CmdVolume.sh 5
binde = , XF86AudioLowerVolume, exec, $scriptsDir/CmdVolume.sh -5
binde = , XF86AudioMute, exec, $scriptsDir/CmdVolume.sh 0

# Player
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Screenshot
bind = $shiftMod, P, exec, $scriptsDir/CmdScreenshot.sh
bind = $altMod, P, exec, hyprshot -m region

# Clipboard History (wofi)
bind = $mainMod, V, exec, $scriptsDir/CmdCliphist.sh

# Silent mode toggle
bind = $mainMod, N, exec, $scriptsDir/OnSilentSwitch.sh

# Lid Switch
bindl = , switch:Lid Switch, exec, $scriptsDir/OnLidSwitch.sh

# PyWal
bind = $mainMod, W, exec, $scriptsDir/CmdPywal.sh
