# STARTUP

#################################################################################
#                                                                               #
#   This config has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this config) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

### SERVICES ###

# XDG Desktop Portals
# exec-once = $scriptsDir/LaunchXDG.sh

# Authentication dialog for GUI Apps
exec-once = $scriptsDir/LaunchPolkit.sh

# Pipewire restart (To avoid bugs)
exec-once = systemctl --user restart pipewire.service

# X11 Settings Daemon
exec-once = systemctl --user start xsettingsd.service

# Notification Daemon
exec-once = $scriptsDir/LaunchMako.sh

# Screen Brightness
exec-once = brightnessctl set 80%

# Wallpaper
exec-once = hyprpaper

# IDLE
exec-once = hypridle

### TRAY ###

# Network
exec-once = hyprctl dispatch exec "sleep 5s && nm-applet --indicator"

# Bluetooth
exec-once = hyprctl dispatch exec "sleep 5s && blueman-applet"

# Password Manager (1Password)
exec-once = hyprctl dispatch exec "sleep 5s && 1password --silent --enable-features=UseOzonePlatform --ozone-platform=x11"

### UTILITIES

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store # Text
exec-once = wl-paste --type image --watch cliphist store # Images

# Udiskie
exec-once = udiskie &

# EasyEffects
exec-once = easyeffects --gapplication-service

# Waybar
exec-once = $scriptsDir/LaunchWaybar.sh

# PyWal
exec-once = $scriptsDir/ChangePalette.sh
