# STARTUP

#################################################################################
#                                                                               #
#   This config has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this config) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################


# XDG Desktop Portals
exec-once = ~/.config/hypr/scripts/XDGDesktopPortal.sh

# Authentication dialog for GUI Apps
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Pipewire restart (To avoid bugs)
exec-once = systemctl --user restart pipewire.service

# X11 Settings Deamon
exec-once = xsettingsd

# Top Bar
exec-once = ~/.config/hypr/scripts/WaybarLaunch.sh

# Notification Daemon
exec-once = ~/.config/hypr/scripts/DunstLaunch.sh

# Screen Brightness
exec-once = brightnessctl set 80%

# Wallpaper
exec-once = hyprpaper

# IDLE
exec-once = hypridle

### TRAY ###

# Network
exec-once = nm-applet --indicator
exec-once = sleep 2

# Bluetooth
exec-once = blueman-applet
exec-once = sleep 2

exec-once = bleman-tray
exec-once = sleep 2

# Password Manager (1Password)
exec-once = 1password --silent --enable-features=UseOzonePlatform --ozone-platform=x11
exec-once = sleep 2

### UTILITIES

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store # Text
exec-once = wl-paste --type image --watch cliphist store # Images

# Udiskie
exec-once = udiskie &

# EasyEffects
exec-once = easyeffects --gapplication-service

# PyWal
exec-once = $scriptsDir/ChangePalette.sh
