# WINDOW RULES

#################################################################################
#                                                                               #
#   This config has been written by angelobdev                                  #
#   It should be used in a properly configured Hyprland environment.            #
#                                                                               #
#   Look at the full configuration here: https://github.com/angelobdev/dotfiles #
#                                                                               #
#   The project (as well as this config) goes under the GNU GPLv3 LICENSE.      #
#                                                                               #
#################################################################################

# Suppress Maximize
windowrulev2 = suppressevent maximize, class:.*

# 1Password
windowrulev2 = float, title:(1Password)
windowrulev2 = size 70% 70%, title:(1Password)
windowrulev2 = center, title:(1Password)

# Electron Dev
windowrulev2 = float, title:(WayOut)
windowrulev2 = center, title:(WayOut)

# Steam
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
