#######################
#      Hyprpaper      #
#######################

wallpaper {
    monitor =
    path = /home/angelo/Downloads/gnome-glass-chip.png
    fit_mode = cover
}

splash = false
splash_offset = 2
splash_color = 55ffff

ipc = true

