plugin {
    touch_gestures {
        
        # Edge swipes
        hyprgrass-bind = , edge:r:l, workspace, +1
        hyprgrass-bind = , edge:l:r, workspace, -1
        hyprgrass-bind = , edge:d:u, exec, pkill -x wvkbd-mobintl || wvkbd-mobintl -L 300   
        hyprgrass-bind = , edge:u:d, exec, $scripts/wofi.sh

        # Window
        hyprgrass-bindm = , longpress:2, movewindow
        hyprgrass-bindm = , longpress:3, resizewindow

        # Left edge
        hyprgrass-bind = , edge:l:u, exec, swayosd-client --brightness raise
        hyprgrass-bind = , edge:l:d, exec, swayosd-client --brightness lower

        # Right edge
        hyprgrass-bind = , edge:r:u, exec, swayosd-client --output-volume raise
        hyprgrass-bind = , edge:r:d, exec, swayosd-client --output-volume lower

        # Tap
        hyprgrass-bind = , tap:3, exec, foot

    }
}