plugin {
    touch_gestures {
        # Edge swipes
        hyprgrass-bind = , edge:r:l, workspace, +1
        hyprgrass-bind = , edge:l:r, workspace, -1
        hyprgrass-bind = , edge:d:u, exec, pkill -x wvkbd-mobintl || wvkbd-mobintl -L 300
        hyprgrass-bind = , edge:u:d, exec, $scripts/wofi.sh

        # Window gestures
        hyprgrass-bindm = , longpress:2, movewindow
        hyprgrass-bindm = , longpress:3, resizewindow

        # Left edge — volume
        hyprgrass-bind = , edge:l:u, exec, $scripts/change-volume.sh --up
        hyprgrass-bind = , edge:l:d, exec, $scripts/change-volume.sh --down

        # Right edge — volume
        hyprgrass-bind = , edge:r:u, exec, $scripts/change-volume.sh --up
        hyprgrass-bind = , edge:r:d, exec, $scripts/change-volume.sh --down

        # Tap
        hyprgrass-bind = , tap:3, exec, foot
    }
}